"""word table

Revision ID: 477158b68436
Revises: 
Create Date: 2020-03-27 04:01:53.540710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477158b68436'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_word'), 'word', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_word'), table_name='word')
    op.drop_table('word')
    # ### end Alembic commands ###
